export interface StyleByStyleAnalysis {
	description: string;
	generalCharacteristics: string[];
	canBePerceivedAs: string[];
	occupationalCharacteristics: string[];
	intensity: string[];
	antagonisticEnvironment: string[];
	emotion: string[];
	words: string[];
}

export const dStyle: StyleByStyleAnalysis = {
	description:
		'People with D personalities tend to be confident and place an emphasis on accomplishing bottom-line results.',
	generalCharacteristics: [
		'Strong Willed',
		'Resolute',
		'Productive',
		'Impetuous',
		'Decisive',
		'Exerts sound leadership',
		'Practical',
		'Establishes goals',
		'Visionary',
		'Can be too busy for family',
		'Optimistic',
		'Impatient with poor performance',
		'Courageous',
		'Knows the right answer',
		'Likes to lead',
		'Has little need for friends',
		'Compulsive need for change',
		'Very independent',
		'Must correct wrongs',
		`Reluctant to say "I'm sorry."`,
		'Not easily discouraged',
		'Excels in emergencies',
		"Won't give up when losing",
		'May be right, but unpopular',
		'Independent and self sufficient',
	],
	canBePerceivedAs: [
		'Overly dominant',
		'Unsympathetic and cold',
		'Insensitive and inconsiderate',
		'Blunt and sarcastic',
		'Unforgiving',
		'Self sufficient and domineering',
		'Argumentative and impatient',
		'Opinionated',
		'Crafty',
		'Not complimentary or emotional',
		'Quick to anger',
	],
	occupationalCharacteristics: [
		'Organises well',
		'Seeks practical solutions',
		'Moves quickly to action',
		'Delegates work',
		'Insists on production',
		'Stimulates activity',
		'Thrives on opposition',
		'Goal orientated',
		'Sees the whole picture',
		'Low tolerance for error',
		"Doesn't analyse details",
		'Bored by trivia',
		'Rash decision-maker',
		'Rude or tactless',
		'Manipulative and demanding',
		'End justifies the means',
		'Demands loyalty in the ranks',
		'Work may become all consuming ',
	],
	intensity: [
		"The higher the 'D value' the more active and aggressive an individual will be whilst overcoming problems and obstcles.",
		"The lower the 'D value' the less of a need to be in control or in a lead position.",
	],
	antagonisticEnvironment: ['High D types will respond aggressively and decisively'],
	emotion: [
		"The 'D' factor can also measure the emotion of anger",
		"The high 'D' may be quick to anger",
		"The low 'D' may be slow to anger.",
	],
	words: ['Dominant', 'Direct', 'Decisive', 'Determined', 'Driven', 'Demanding', 'Doer', 'Daring'],
};

export const iStyle: StyleByStyleAnalysis = {
	description:
		'People with i personalities tend to be more open and place an emphasis on relationships and influencing or persuading others.',
	generalCharacteristics: [
		'Outgoing", "Charismatic',
		'Warm',
		'Friendly',
		'Talkative',
		'Life of the party',
		'Compassionate',
		'Demonstrative',
		'Generous',
		'Sincere at heart',
		'Good sense of humour',
		'Positive ',
		'Memory for stories',
		'Enthusiastic',
		'Expressive',
		'Good on stage',
		'Wide-eyed',
		'Innocent',
		'Lives in the present',
		'Changeable disposition',
		'Compulsive talker',
		'Exaggerates',
		'Optimistic ',
	],
	canBePerceivedAs: [
		'Undisciplined',
		'Weak-willed',
		'Restless',
		'Naive',
		'Disorganised',
		'Unproductive',
		'Undependable',
		'Over-optimistic',
		'Egocentric',
		'Dwells on trivia',
		'Controlled by circumstances',
		'Angers easily ',
	],
	occupationalCharacteristics: [
		'Volunteers for jobs',
		'Thinks up new activities',
		'Looks great on the surface',
		'Creative and colourful',
		'Has energy and enthusiasm',
		'Starts in a flashy way',
		'Inspires others to join in',
		'Charms others to work',
		'Wastes time talking',
		'Would rather talk than work',
		'Forgets obligations',
		'Does not follow through',
		'Easily distracted',
		'Confidence fades fast',
		'Undisciplined',
		'Does not always prioritise',
		'Decides by feelings',
	],
	intensity: [
		"The higher the 'I value' the more active, verbal and persuasive an individual will be whilst overcoming problems and obstacles.",
		"The lower the 'I value' the more the person will use data and facts with a tendency to be more non-verbal.",
	],
	antagonisticEnvironment: ['High I types will respond actively and may try to negotiate an agreement.'],
	emotion: [
		"The 'I' Factor measures the emotion of optimism. Extremly high 'I's' are joyfull and optimistic. Low 'I's' tend to be more pessimistic.",
	],
	words: [
		'Influencing',
		'Inspiring',
		'Impulsive',
		'Impatient',
		'Impressionable',
		'Interpersonal',
		'Intuitive',
		'Involved',
	],
};

export const sStyle: StyleByStyleAnalysis = {
	description: 'People with S personalities tend to be dependable and place an emphasis on cooperation and sincerity.',
	generalCharacteristics: [
		'Likable',
		'Efficient',
		'Dependable',
		'Practical',
		'Low-key personality',
		'Relaxed',
		'Well Balanced',
		'Sympathetic',
		'Keeps emotion hidden',
		'Diplomatic',
		'Organised',
		'Conservative',
		'Reluctant Leader',
		'Easy going',
		'Patient',
		'Quiet, but witty',
		'Kind',
		'Happily reconciled to life',
	],
	canBePerceivedAs: [
		'Unmotivated',
		'Blasé',
		'Spectator',
		'Self-protective',
		'Indecisive',
		'Fearful',
		'Unenthusiastic',
		'Reticent',
		'Avoids responsibility',
		'Passive resistance',
		'Too compromising',
		'An observer',
	],
	occupationalCharacteristics: [
		'Competent',
		'Steady',
		'Peaceful',
		'Agreeable',
		'Has administrative ability',
		'Mediates problems',
		'Avoids conflicts',
		'Finds the easy way',
		'Resents being pushed',
		'Lacks self-motivation',
		'Not goal oriented',
		'Desire to complete tasks',
	],
	intensity: [
		"The higher the 'S value', the slower a person will undertake activities. The more the person prefers to start and complete one project at a time.",
		"The higher the 'S' the more resistant to change.",
		"The lower the 'S' value, the faster the pace and greater the desire for change.",
	],
	antagonisticEnvironment: ['High S types will respond passively/aggressively and seek to blend in. '],
	emotion: [
		"The 'S' factor' measures emotional expression.",
		"The higher the 'S' value, the more difficult it is to read an individual. The lower the 'S' factor, the more emotionally expressive.",
	],
	words: ['Stready', 'Stable', 'Sincere', 'Supportive', 'Shy', 'Status quo', 'Security', 'Sensitive'],
};

export const cStyle: StyleByStyleAnalysis = {
	description: 'People with C personalities tend to place an emphasis on quality, accuracy, expertise, and competency.',
	generalCharacteristics: [
		'Analytical',
		'Perfectionist',
		'Loyal',
		'Self-sacrificing',
		'Serious',
		'Genius prone',
		'Creative',
		'Musically gifted',
		'Idealistic',
		'Conscientious',
		'Sensitive',
		'Self-disciplined',
		'Purposeful',
		'Talented',
		'Artistic',
		'Philosophical ',
	],
	canBePerceivedAs: [
		'Moody',
		'Negative',
		'Critical',
		'Rigid',
		'Legalistic',
		'Sensitive to criticism',
		'Revengeful',
		'Unsociable',
		'Theoretical',
		'Impractical',
		'Becoming depressed over imperfections',
		'Not people orientated',
		'Hard to please',
	],
	occupationalCharacteristics: [
		'Schedule oriented',
		'Perfectionist',
		'High standards',
		'Detail orientated',
		'Persistent',
		'Thorough',
		'Orderly',
		'Organised',
		'Economical',
		'Sees the problem',
		'Finds creative solutions',
		'Needs to finish what he/she starts',
		'Likes charts, graphs, figures',
		'Prefers analysis to work',
		'Can spend too much time planning',
		'Deep need for approval ',
	],
	intensity: [
		"The higher the 'C value' the more the person will comply with rules set by others.",
		"The lower the 'C value', the more an individual will challenge rules and seek independence.",
	],
	antagonisticEnvironment: ['High C types will respond passively/aggressively and seek to justify their actions.'],
	emotion: [
		"The 'C' factor measures caution. The higher the 'C' value, the more cautious the person. The lower the 'C' value, the more fearless the individual.",
	],
	words: [
		'Cautious',
		'Compliant',
		'Consitent',
		'Calculating',
		'Conscientous',
		'Competent',
		'Careful',
		'Paralysis of analysis',
	],
};
